spring:
  redis:
    host: 127.0.0.1
    port: 6379
#    cluster:
#      nodes:
#        - 120.25.219.234:9001
#        - 120.25.219.234:9002
#        - 120.25.219.234:9003
#        - 120.25.219.234:9004
#        - 120.25.219.234:9005
#        - 120.25.219.234:9006
#      max-redirects: 3    # 获取失败 最大重定向次数

    password: z5201314
    database: 0   #redis数据库索引，默认为0
    jedis:
      pool:   #连接池配置
        max-active: 4   #连接池最大连接数
        max-wait: -1    #连接池最大阻塞等待时间
        max-idle: 4     #连接池中的最大空闲连接数
        min-idle: 0     #连接池中的最小空闲连接数
